name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    runs-on: ubuntu-24.04
    needs:
      - build
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.ELEMENT_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: lts/krypton
          cache: 'npm'
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: dist
          path: dist
      - run: npm ci --prefer-offline --no-audit
      - run: npx semantic-release
        env:
          GIT_AUTHOR_NAME: 'Siemens Element Bot'
          GIT_AUTHOR_EMAIL: 'simpl.si@siemens.com'
          GIT_COMMITTER_NAME: 'Siemens Element Bot'
          GIT_COMMITTER_EMAIL: 'simpl.si@siemens.com'
          GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_GITHUB_TOKEN }}
